-- Paquete: FIDE_PAQUETE


CREATE OR REPLACE PACKAGE FIDE_PAQUETE IS

    -- Funciones
    FUNCTION FIDE_CLIENTE_TB_OBTENER_NOMBRE_COMPLETO_FN(p_id_cliente NUMBER) RETURN VARCHAR2;
    FUNCTION FIDE_CLIENTE_TB_CONTAR_POR_TIPO_FN(p_id_tipo_cliente NUMBER) RETURN NUMBER;
    FUNCTION FIDE_CLIENTE_TB_EXISTE_CORREO_FN(p_email VARCHAR2) RETURN NUMBER;
    FUNCTION FIDE_PUESTO_TRABAJO_TB_OBTENER_SALARIO_FN(p_id_puesto NUMBER) RETURN NUMBER;
    FUNCTION FIDE_PUESTO_TRABAJO_TB_LISTAR_POR_ESTADO_FN(p_id_estado NUMBER) RETURN VARCHAR2;
    FUNCTION FIDE_ESTADO_TB_OBTENER_DESCRIPCION_FN(p_id_estado NUMBER) RETURN VARCHAR2;
    FUNCTION FIDE_TIPO_CLIENTE_TB_DESCRIPCION_POR_ID_FN(p_id_tipo_cliente NUMBER) RETURN VARCHAR2;
    FUNCTION FIDE_PROVINCIA_TB_OBTENER_NOMBRE_FN(p_id_provincia NUMBER) RETURN VARCHAR2;
    FUNCTION FIDE_CANTON_TB_OBTENER_NOMBRE_FN(p_id_canton NUMBER) RETURN VARCHAR2;
    FUNCTION FIDE_DISTRITO_TB_OBTENER_NOMBRE_FN(p_id_distrito NUMBER) RETURN VARCHAR2;
    FUNCTION FIDE_SUCURSAL_TB_OBTENER_EMAIL_FN(p_id_sucursal NUMBER) RETURN VARCHAR2;
    FUNCTION FIDE_DIRECCION_TB_OBTENER_COMPLETA_FN(p_id_sucursal NUMBER) RETURN VARCHAR2;
    FUNCTION FIDE_CLIENTE_TB_TELEFONO_POR_ID_FN(p_id_cliente NUMBER) RETURN NUMBER;
    FUNCTION FIDE_CLIENTE_TB_ESTADO_POR_ID_FN(p_id_cliente NUMBER) RETURN NUMBER;
    FUNCTION FIDE_CLIENTE_TB_LISTAR_POR_ESTADO_FN(p_id_estado NUMBER) RETURN VARCHAR2;

    -- Procedimientos (declaraciones)
    PROCEDURE FIDE_ESTADO_TB_INSERTAR_SP(p_id_estado IN NUMBER, p_estado IN VARCHAR2, p_descripcion_estado IN VARCHAR2);
    PROCEDURE FIDE_ESTADO_TB_OBTENER_SP(p_resultado OUT SYS_REFCURSOR, p_id_estado FIDE_ESTADO_TB.id_estado%TYPE);
    PROCEDURE FIDE_ESTADO_TB_ACTUALIZAR_SP(p_id_estado IN NUMBER, p_estado IN VARCHAR2, p_descripcion_estado IN VARCHAR2);

    

END FIDE_PAQUETE;
/

CREATE OR REPLACE PACKAGE BODY FIDE_PAQUETE IS

    -- Funciones
    FUNCTION FIDE_CLIENTE_TB_OBTENER_NOMBRE_COMPLETO_FN(p_id_cliente NUMBER) RETURN VARCHAR2 IS
        v_nombre_completo VARCHAR2(200);
    BEGIN
        SELECT NOMBRE_CLIENTE || ' ' || PRIMER_APELLIDO || ' ' || SEGUNDO_APELLIDO
        INTO v_nombre_completo
        FROM FIDE_CLIENTE_TB
        WHERE ID_CLIENTE = p_id_cliente;
        RETURN v_nombre_completo;
    END;

    FUNCTION FIDE_CLIENTE_TB_CONTAR_POR_TIPO_FN(p_id_tipo_cliente NUMBER) RETURN NUMBER IS
        v_total NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_total FROM FIDE_CLIENTE_TB WHERE ID_TIPO_CLIENTE = p_id_tipo_cliente;
        RETURN v_total;
    END;

    FUNCTION FIDE_CLIENTE_TB_EXISTE_CORREO_FN(p_email VARCHAR2) RETURN NUMBER IS
        v_existe NUMBER;
    BEGIN
        SELECT COUNT(*) INTO v_existe FROM FIDE_CLIENTE_TB WHERE EMAIL = p_email;
        RETURN CASE WHEN v_existe > 0 THEN 1 ELSE 0 END;
    END;

    FUNCTION FIDE_PUESTO_TRABAJO_TB_OBTENER_SALARIO_FN(p_id_puesto NUMBER) RETURN NUMBER IS
        v_salario NUMBER;
    BEGIN
        SELECT SALARIO INTO v_salario FROM FIDE_PUESTO_TRABAJO_TB WHERE ID_PUESTO_TRABAJO = p_id_puesto;
        RETURN v_salario;
    END;

    FUNCTION FIDE_PUESTO_TRABAJO_TB_LISTAR_POR_ESTADO_FN(p_id_estado NUMBER) RETURN VARCHAR2 IS
        v_lista VARCHAR2(1000);
    BEGIN
        SELECT LISTAGG(ID_PUESTO_TRABAJO, ',') WITHIN GROUP (ORDER BY ID_PUESTO_TRABAJO)
        INTO v_lista FROM FIDE_PUESTO_TRABAJO_TB WHERE ID_ESTADO = p_id_estado;
        RETURN v_lista;
    END;

    FUNCTION FIDE_ESTADO_TB_OBTENER_DESCRIPCION_FN(p_id_estado NUMBER) RETURN VARCHAR2 IS
        v_desc VARCHAR2(500);
    BEGIN
        SELECT DESCRIPCION_ESTADO INTO v_desc FROM FIDE_ESTADO_TB WHERE ID_ESTADO = p_id_estado;
        RETURN v_desc;
    END;

    FUNCTION FIDE_TIPO_CLIENTE_TB_DESCRIPCION_POR_ID_FN(p_id_tipo_cliente NUMBER) RETURN VARCHAR2 IS
        v_desc VARCHAR2(300);
    BEGIN
        SELECT DESCRIPCION INTO v_desc FROM FIDE_TIPO_CLIENTE_TB WHERE ID_TIPO_CLIENTE = p_id_tipo_cliente;
        RETURN v_desc;
    END;

    FUNCTION FIDE_PROVINCIA_TB_OBTENER_NOMBRE_FN(p_id_provincia NUMBER) RETURN VARCHAR2 IS
        v_nombre VARCHAR2(50);
    BEGIN
        SELECT NOMBRE_PROVINCIA INTO v_nombre FROM FIDE_PROVINCIA_TB WHERE ID_PROVINCIA = p_id_provincia;
        RETURN v_nombre;
    END;

    FUNCTION FIDE_CANTON_TB_OBTENER_NOMBRE_FN(p_id_canton NUMBER) RETURN VARCHAR2 IS
        v_nombre VARCHAR2(50);
    BEGIN
        SELECT NOMBRE_CANTON INTO v_nombre FROM FIDE_CANTON_TB WHERE ID_CANTON = p_id_canton;
        RETURN v_nombre;
    END;

    FUNCTION FIDE_DISTRITO_TB_OBTENER_NOMBRE_FN(p_id_distrito NUMBER) RETURN VARCHAR2 IS
        v_nombre VARCHAR2(255);
    BEGIN
        SELECT NOMBRE_DISTRITO INTO v_nombre FROM FIDE_DISTRITO_TB WHERE ID_DISTRITO = p_id_distrito;
        RETURN v_nombre;
    END;

    FUNCTION FIDE_SUCURSAL_TB_OBTENER_EMAIL_FN(p_id_sucursal NUMBER) RETURN VARCHAR2 IS
        v_email VARCHAR2(250);
    BEGIN
        SELECT EMAIL INTO v_email FROM FIDE_SUCURSAL_TB WHERE ID_SUCURSAL = p_id_sucursal;
        RETURN v_email;
    END;

    FUNCTION FIDE_DIRECCION_TB_OBTENER_COMPLETA_FN(p_id_sucursal NUMBER) RETURN VARCHAR2 IS
        v_direccion VARCHAR2(500);
    BEGIN
        SELECT DETALLE_DIRECCION || ', ' || ID_DISTRITO || ', ' || ID_CANTON || ', ' || ID_PROVINCIA
        INTO v_direccion FROM FIDE_DIRECCION_TB WHERE ID_SUCURSAL = p_id_sucursal;
        RETURN v_direccion;
    END;

    FUNCTION FIDE_CLIENTE_TB_TELEFONO_POR_ID_FN(p_id_cliente NUMBER) RETURN NUMBER IS
        v_telefono NUMBER;
    BEGIN
        SELECT NUM_TELEFONO INTO v_telefono FROM FIDE_CLIENTE_TB WHERE ID_CLIENTE = p_id_cliente;
        RETURN v_telefono;
    END;

    FUNCTION FIDE_CLIENTE_TB_ESTADO_POR_ID_FN(p_id_cliente NUMBER) RETURN NUMBER IS
        v_estado NUMBER;
    BEGIN
        SELECT ID_ESTADO INTO v_estado FROM FIDE_CLIENTE_TB WHERE ID_CLIENTE = p_id_cliente;
        RETURN v_estado;
    END;

    FUNCTION FIDE_CLIENTE_TB_LISTAR_POR_ESTADO_FN(p_id_estado NUMBER) RETURN VARCHAR2 IS
        v_lista VARCHAR2(1000);
    BEGIN
        SELECT LISTAGG(ID_CLIENTE, ',') WITHIN GROUP (ORDER BY ID_CLIENTE)
        INTO v_lista FROM FIDE_CLIENTE_TB WHERE ID_ESTADO = p_id_estado;
        RETURN v_lista;
    END;

    
    PROCEDURE FIDE_ESTADO_TB_INSERTAR_SP(p_id_estado IN NUMBER, p_estado IN VARCHAR2, p_descripcion_estado IN VARCHAR2) IS
    BEGIN
        INSERT INTO FIDE_ESTADO_TB (ID_ESTADO, ESTADO, DESCRIPCION_ESTADO)
        VALUES (p_id_estado, p_estado, p_descripcion_estado);
    END;

    PROCEDURE FIDE_ESTADO_TB_OBTENER_SP(p_resultado OUT SYS_REFCURSOR, p_id_estado FIDE_ESTADO_TB.id_estado%TYPE) IS
    BEGIN
        IF p_id_estado IS NULL THEN
            OPEN p_resultado FOR
            SELECT ID_ESTADO, ESTADO, DESCRIPCION_ESTADO FROM FIDE_ESTADO_TB;
        ELSE
            OPEN p_resultado FOR
            SELECT ID_ESTADO, ESTADO, DESCRIPCION_ESTADO FROM FIDE_ESTADO_TB
            WHERE ID_ESTADO = p_id_estado;
        END IF;
    END;

    PROCEDURE FIDE_ESTADO_TB_ACTUALIZAR_SP(p_id_estado IN NUMBER, p_estado IN VARCHAR2, p_descripcion_estado IN VARCHAR2) IS
    BEGIN
        UPDATE FIDE_ESTADO_TB
        SET ESTADO = p_estado,
            DESCRIPCION_ESTADO = p_descripcion_estado
        WHERE ID_ESTADO = p_id_estado;
    END;

END FIDE_PAQUETE;
/
